name: Blog-App-Deploy-to-Netlify

on: [push, repository_dispatch]

jobs:
  build:
    name: Deploying Blog App
    runs-on: ubuntu-latest
    environment: firebase
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: install packages and make build
        run: cd blog && npm install && npm run build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          GATSBY_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          GATSBY_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          GATSBY_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          GATSBY_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          GATSBY_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      - name: Netlify Deploy
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: './blog/public'
          production-branch: main
          production-deploy: true
          github-deployment-environment: firebase
          deploy-message: '${{ github.event.head_commit.message }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_SITE_ID }}
