name: Diaries

on: [push]

jobs:
  build:
    name: Deploying to surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Prepare for Yarn Installation
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - name: install yarn
        run: sudo apt update && sudo apt install yarn
      - name: instaling dependencies
        run: yarn --cwd ./diaries-app install
      - name: Build Diaries app
        run: yarn --cwd ./diaries-app build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./diaries-app/build bootcamp-2020_diaries_app.surge.sh --token ${{ secrets.SURGE_TOKEN }}
