name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Prepare for Yarn Installation
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - name: install yarn
        run: sudo apt update && sudo apt install yarn
      - name: instaling dependencies
        run: yarn --cwd ./expense-tracker-app install
      - name: Build Expense Tracker App
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.APIKEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.AUTHDOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.PROJECTID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.STORAGEBUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGINGSENDERID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.APPID }}
          REACT_APP_DATABASE_URL: ${{ secrets.DATABASEURL }}
        run: yarn --cwd ./expense-tracker-app build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./expense-tracker-app/build bootcamp-2020_expense_tracker_app.surge.sh --token ${{ secrets.SURGE_TOKEN }}
